vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/public/images/products'
  #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
  mappings:
    image:
      uri_prefix: /uploads/images
      upload_destination: '%kernel.project_dir%/public/uploads/images'
      namer: Vich\UploaderBundle\Naming\OrignameNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    media_file:
      uri_prefix: /media_files
      upload_destination: '%kernel.project_dir%/public/uploads/medias'
      namer: Vich\UploaderBundle\Naming\OrignameNamer
