name: 'my_collection'
version: '3.8'

services:
    php:
        ports: [ "8307" ]
        build:
            context: .
            dockerfile: Dockerfile
            target: mycollection
        links:
            - database
        restart: unless-stopped
        volumes:
            - ./:/var/www/html:rw,cached
            - ./unix:/var/run/php
        environment:
            APP_ENV: local

    web:
        image: nginx:latest
        ports:
            - "8081:80"
            - "8306:8307"
        links:
            - php
        volumes:
            - ./:/var/www/html:ro
            - ./docker/nginx:/etc/nginx/conf.d
            - ./unix:/var/run/php

    database:
        image: mysql:8
        platform: linux/amd64
        deploy:
            restart_policy:
                condition: on-failure
        ports:
            - "3309:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=mycollection
            - MYSQL_USER=api
            - MYSQL_PASSWORD=password

    memcached:
        image: 'memcached:latest'
        ports:
            - "11211:11211"

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
