# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Provider/'
    
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    App\Serializer\GenericContextBuilder:
        decorates: 'api_platform.serializer.context_builder'
        arguments:
            - '@App\Serializer\GenericContextBuilder.inner'
            - '@security.helper'
            - '@security.role_hierarchy'
        autoconfigure: false
    
    App\Provider\CollectionProvider:
        arguments:
            - '@security.helper'
            - '@doctrine'
            - !tagged api_platform.doctrine.orm.query_extension.collection
            - '@api_platform.iri_converter'
        tags: [ 'api_platform.state_provider' ]
        
    App\Processor\CollectionProcessor:
        arguments:
            - '@security.helper'
            - '@doctrine'
            - '@api_platform.iri_converter'
        tags: [ 'api_platform.state_processor' ]
        
    App\Processor\ItemProcessor:
        arguments:
            - '@security.helper'
            - '@doctrine'
            - '@api_platform.iri_converter'
        tags: [ 'api_platform.state_processor' ]
        
    App\EventListener\ExceptionListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception' }
                
    App\EventListener\DoctrineListener\UpdateDateListener:
        tags:
            -   name: 'doctrine.orm.entity_listener'
                event: 'preUpdate'
                entity: 'App\Entity\Resource'
                
            -   name: 'doctrine.orm.entity_listener'
                event: 'preUpdate'
                entity: 'App\Entity\Collection'
                
            -   name: 'doctrine.orm.entity_listener'
                event: 'preUpdate'
                entity: 'App\Entity\Item'
                
            -   name: 'doctrine.orm.entity_listener'
                event: 'preUpdate'
                entity: 'App\Entity\Price'
    
    App\EventListener\DoctrineListener\UserPasswordEncodeListener:
        arguments:
            - '@security.user_password_hasher'
        tags:
            -   name: 'doctrine.orm.entity_listener'
                event: 'prePersist'
                entity: 'App\Entity\User'
